### PR TITLE
Split up the work from #339

### PR DESCRIPTION
**Pull request by arlolra**

### CODE REVIEW

**Comment by dmajda** [comment]
It would be great to separate the “run `make hint`” change from the “test against other Node versions” change — they are logically separate.

**Comment by dmajda** [comment]
Added a bunch of comments (which mostly disappeared meanwhile — you apparently push-forced). With the mentioned issues fixed I’d be glad to merge.

**Comment by arlolra** [comment]
Should be as desired now.

**Comment by dmajda** [comment]
Thanks!

**Pull request merged**
