### PR TITLE
Add code coverage by Istanbul

### PR DESCRIPTION
**Pull request by Mingun**
I also plan try to add one of coverage sites, https://coveralls.io/ maybe.

### CODE REVIEW

**Comment by Mingun** [comment]
I try to setup coverage reports:
* [Coveralls](https://coveralls.io/) -- see example report: https://coveralls.io/builds/14692001/source?filename=lib%2Fcompiler%2Fpasses%2Fgenerate-js.js
* [Codecov](https://codecov.io) -- see example report: https://codecov.io/gh/Mingun/pegjs/src/208b2518caef6efbda35e17a532f796dc3cea470/lib/compiler/passes/generate-js.js

Unfortunately, at both websites of a problem with a usability when viewing reports -- it is not clear that the color coloring of lines means. But coveralls was pleasant to me more the fact that there at least there is a navigation on uncovered lines.

Сovering percent at badge at the different websites differs, because coveralls calculates aggregate percent from line & branch coverage, but codecov show only line coverage.

If one of these websites arranges, I can add commit to this PR or make new PR

**Comment by futagoza** [comment]
I've already setup PEG.js on Coveralls when I saw this PR: https://coveralls.io/github/pegjs/pegjs
I'm guessing once this PR is merged, Coveralls will run automatically with each commit like Travis does?

**Comment by pjmolina** [comment]
In fact,  there is a plugin for both to report the coverage. When the CI runs (travis or circleci) one of the steps reports the coverage. See a [sample](https://github.com/metadevpro/baucis-openapi3/blob/master/.travis.yml)  here with travis + coveralls

**Comment by Mingun** [comment]
> I'm guessing once this PR is merged, Coveralls will run automatically with each commit like Travis does?

No, some simple setup required (see [changes](https://github.com/Mingun/pegjs/compare/coverage...coveralls)).

**Comment by Mingun** [comment]
Now this ready to merge. As you can see, integration works.

**Pull request merged**
