### PR TITLE
Auto-add `allowedStartRules` to test options for `changeAST` method if it not defined

### PR DESCRIPTION
**Pull request by Mingun**
[As requested](https://github.com/pegjs/pegjs/pull/399#discussion_r146111960)

### CODE REVIEW

**Comment by Mingun** [comment]
@futagoza?

**Comment by futagoza** [comment]
Sorry @Mingun, I'm currently busy with something personal but am working on the [development-overhaul branch](https://github.com/pegjs/pegjs/tree/development-overhaul), but will do the merge for this PR and the other PR's after I merge my branch with the master branch.

By the way, on my [development-overhaul branch](https://github.com/pegjs/pegjs/tree/development-overhaul) I've moved the spec and benchmark test's into separate folder's within the test directory, and also moved [tools/impact](https://github.com/pegjs/pegjs/blob/master/tools/impact) to [test/impact](https://github.com/pegjs/pegjs/blob/development-overhaul/test/impact). I've also separated the server logic from benchmark and spec into [test/server](https://github.com/pegjs/pegjs/tree/development-overhaul/test).

Since you have open PR's that include's tests, do you want me to move the folder's back until I've merged your PR's, or are you willing to update your PR's?

**Comment by Mingun** [comment]
I will update PRs. I have an extensive experience in it :/.

Just I wanted to learn whether there are some remarks which need to be considered because I have some more works depending on some PRs

**Comment by futagoza** [comment]
Ok, if that's the case I'll check your PR's again tonight

**Comment by Mingun** [comment]
So what? Finita la commedia :(?

**Comment by futagoza** [comment]
sorry, got some stuff going on, but I haven't forgotten 😄 

I've merged the development-overhaul branch into master, so you can go ahead and update your PR's (take note of the changes I've done, and make sure you're updates follow these changes), after that I'll merge them.

**Pull request merged**
