### PR TITLE
Allow unbalanced braces

### LINKED ISSUE #352: Rules can't contain quoted braces unless they are balanced
The grammar for peg.js rules says:
```
SourceCharacter
  = .

CodeBlock "code block"
  = "{" code:Code "}" { return code; }

Code
  = $((![{}] SourceCharacter)+ / "{" Code "}")*
```

This means that the following causes a syntax error:
```
myrule = "{" { return "{"; }
```
because the quoted brace is unbalanced.

A fix would be something like:
```
Code
  = $(Comment / StringLiteral / (![{}"'] SourceCharacter)+ / "{" Code "}")*
```
Which would allow braces and quotes (even unbalanced ones!) in comments or string literals.

### PR DESCRIPTION
**Pull request by arlolra**
* Fixes #352

### CODE REVIEW

**Comment by cscott** [comment]
Look good, I like the test cases.

The RegExp grammar might be a little bit of overkill, you don't need to parse regexps that precisely, you just need to parse enough to ensure you can find the closing delimiter.  For example, there's no need to parse the flags, that can just get swallowed by the general SourceCharacter production inside Code.  You can't have any special characters or escapes in the flags, so you don't need to actually parse them.

That said, sticking to the ES6 production names (as you have) will make it easier for readers to follow the grammar, so that's probably worth a bit of spurious precision.

+1

**Comment by dmajda** [comment]
Your code doesn’t handle cases like this (the action is a perfectly valid JavaScript):

    start = "a" { return ({ a: 1 / 2 }) / 3; }

A more sophisticated approach is needed.

In any case, #89 is marked as post-1.0.0, so I won’t spend time on this now, sorry.

**Comment by cscott** [comment]
If you are concerned about that, just drop the RegExpLiteral production from the patch.   That would still handle all unbalanced braces that don't occur in regexps, which is much better than the current situation!

**Comment by cscott** [comment]
jslint uses a simple rule (http://stackoverflow.com/a/11766233), I'll update this patch to do the same.

**Pull request closed without merging**
