### PR TITLE
Custom location parameter for error() and expected() fuctions

### PR DESCRIPTION
**Pull request by YemSalat**
#390

### CODE REVIEW

**Comment by Mingun** [comment]
`lib/parser.js` is auto-generated file. You need change code, that generate it, located in https://github.com/pegjs/pegjs/blob/master/lib/compiler/passes/generate-js.js#L970-L984, and than renererate parser itself with `make parser`.

**Comment by YemSalat** [comment]
My bad, thanks for the explanation, updated the branch*

**Comment by Mingun** [comment]
Correct also the description of functions in `readme.md` and squash all commits into one.

**Comment by YemSalat** [comment]
Done

**Comment by YemSalat** [comment]
Sorry, I really don't want to be annoying as I realize there are plenty of stuff that needs to be merged.
But is there any chance to get this feature in? Would be really useful for my current project.
Thanks!

**Comment by dmajda** [comment]
@YemSalat Thanks for your patch and sorry I didn’t get to it for so long. I looked at it and ultimately decided to [implement the feature myself](https://github.com/pegjs/pegjs/commit/ce44c62f147c2a171fd52f66499205e7b2f89b8e). I figured it will be more expedient than taking your patch through full review cycle, especially given it was few months since you wrote it. I gave you credit in the commit message of course.

My solution differs form yours mainly in more robust handling of the optional `location` argument and in having tests.

**Comment by YemSalat** [comment]
@dmajda no worries! Glad that this got in, will be really useful.
Thanks a lot!

**Pull request closed without merging**
