### PR TITLE
Improve error when reserved word used as label

### PR DESCRIPTION
**Pull request by Mingun**
Before this commit error looks like (for input `start = break:'a'`)

> Expected "!", "$", "&", "(", "*", "+", ".", "/", "/*", "//", ";", "?", character class, code block, comment, end of line, identifier, literal, or whitespace but ":" found.

After this error looks like

> Expected identifier but reserved word "break" found.

(cherry picked from commit 9c8b868f406dc50f1a15690c9938d90034f6025d)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by futagoza** [comment]
In `src/parser.pegjs` can you:

- rename `RESERVED_WORDS_JS` to `RESERVED_WORDS`
- remove `let reservedWords = new Set(RESERVED_WORDS_JS);` in the initializer block
- change the code in the action block for `Identifier` to
```js
if ( RESERVED_WORDS.indexOf(name) === -1 ) return name;
error(`Expected identifier but reserved word "${name}" found.`);
```

The reason for these changes is simple:

1. It is already obvious what these are reserved for, so no need to add the ugly `_JS` postfix
2. Using `Set` will make Babel add a polyfill for it, and we only need to check if `name` exists within the list, so a simple use of `Array#indexOf` is better here.

**Comment by Mingun** [comment]
> It is already obvious what these are reserved for, so no need to add the ugly `_JS` postfix

Potentially the code can be generated not only for JS and reserved keywords will be others. Originally I wanted to add a feature to allow to redefine in options this list (for support of other languages), but now there is no opportunity to supply options which will be used only in compilation stage (#517).

**Comment by Mingun** [comment]
This can't be merged in such way, as it broke, for example, JSON example grammar. `error` and `expected` functions caused immediately reporting error instead of backtraking, and when grammar contains rule with reserved name it dailed to parse, because it firstly try parse `label:experession` and then `expression`/ Example of such grammar:
```
start = false;
false = 'a';
```

**Comment by Mingun** [comment]
But now this problem fixed.

**Comment by futagoza** [comment]
> Potentially the code can be generated not only for JS and reserved keywords will be others. Originally I wanted to add a feature to allow to redefine in options this list (for support of other languages), but now there is no opportunity to supply options which will be used only in compilation stage (#517).

I've taken note of this (facepalmed my self, of course, wondering why I forgot this when I did the same hack my self a while back 😆 ) and will add this after I'm done with the ASTVisitor class.

**Pull request merged**
